### ISSUE TITLE
Collaborate on official VSCode extension 🙏 

### ISSUE THREAD

**Issue by lianmakesthings** [Tchoupinax/tilt-vscode-extension#12]
Hi Tchoupinax,

It's nice to virtually meet you. I'm Lian, Developer Advocate for Tilt, and I wanted to reach out to you to first thank you for your fantastic work on this extension! This was one of the first things I installed to help me get onboarded with Tilt. Well done!

We are now currently working on an official VS Code extension which includes a Starlark LSP server.  The repo is currently private because we are still ironing things out, but as soon as we release (which will be very soon), we will open source it.
We were hoping you'd be willing to contribute to the official extension or collaborate in some other way. We really appreciate all the work you've put into this so far and wouldn't want to see it go to waste.

Please don't hesitate to reach out if you have any more questions or comments, either here or to lian@tilt.dev.

Thanks again and hope you're having a great day :)

**Comment by Tchoupinax** [comment]
Hello @lianmakesthings,

Thank you a lot for your message, it makes me warn in my heart.
I started this project because I used a lot `Tilt` and I was not happy to have a fully white-text file to declare my services. I searched for an extension for this job but I did not find one, so I decided to do this job because I seemed to me accessible.

I'm really happy to read your announcement and can't wait to see this project released. I do not have the pretension of being able to make great and large participates but you can count on me to propose some improvement or directly submit this work (like I sometimes did with [tilt-extensions](https://github.com/tilt-dev/tilt-extensions))

Thanks for your work (and for the great work of Tilt's team)! 
Have a nice day too! :)

**Comment by milas** [comment]
Hi @Tchoupinax , in case you haven't seen it, I wanted to make sure to let you know that we have released an extension that integrates with the new LSP built into Tilt to provide autocomplete & more in addition to syntax highlighting:
 * [Tiltfile extension on VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=tilt-dev.Tiltfile)
 * [tilt-dev/vscode-tilt repo on GitHub](https://github.com/tilt-dev/vscode-tilt/)

Also, I wanted to say thanks again from the Tilt team for all the work you've done on this extension over the years! 🎉🙂
